--- #YAML:1.0
name:               IP-Country
version:            2.27
abstract:           fast lookup of country codes from IP addresses
author:
    - Nigel Wetters Gourlay <nwetters@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Geography::Countries:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
