--- #YAML:1.0
name:                IP-Country
version:             2.22
abstract:            fast lookup of country codes from IP addresses
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Nigel Wetters Gourlay <nwetters@cpan.org>
